'use strict';
// resolveReportUser() must distinguish "session expired" (401 from
// /api/auth/me) from any other failure to reach the server. On a 401 it
// redirects to /login and the download handlers (downloadSummaryReport,
// downloadIncidentReport) must bail out without building or downloading a
// report - never attributing it to "unknown user" while a session actually
// expired mid-use. On any other failure (network error, no server), the
// existing "unknown user" fallback must still apply and the download must
// still happen.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { loadApp } = require('./helpers/load-app');

const LOG_PATH = path.join(__dirname, '..', 'test-data', 'network-incidents.log');
const logText = fs.readFileSync(LOG_PATH, 'utf8');

// Drives the real UI (paste + click #parse) so the module-private `D`/`name`
// state the download handlers close over is populated exactly as it would be
// for a real user, then stubs the browser download primitives jsdom doesn't
// implement (URL.createObjectURL/revokeObjectURL) so downloadHTML() can run
// without throwing.
function setUp() {
  const { window, SyslogLens } = loadApp();
  const doc = window.document;
  doc.querySelector('#paste').value = logText;
  doc.querySelector('#parse').click();
  assert.equal(doc.querySelector('#app').hidden, false, 'log should have parsed and the app view shown');

  const createObjectURLCalls = [];
  window.URL.createObjectURL = (blob) => { createObjectURLCalls.push(blob); return 'blob:stub'; };
  window.URL.revokeObjectURL = () => {};

  // Select an incident so downloadIncidentReport() has one to report on.
  doc.querySelector('.sv[data-s="5"]').click();
  const incBtn = doc.querySelector('#list .inc');
  if (incBtn) incBtn.click();

  return { window, SyslogLens, createObjectURLCalls };
}

test('a 401 from /api/auth/me redirects to /login and downloadSummaryReport does not download anything', async () => {
  const { window, SyslogLens, createObjectURLCalls } = setUp();
  window.fetch = async () => ({ status: 401 });

  await SyslogLens.downloadSummaryReport();

  assert.equal(createObjectURLCalls.length, 0, 'no report should be downloaded when the session has expired');
});

test('a 401 from /api/auth/me redirects to /login and downloadIncidentReport does not download anything', async () => {
  const { window, SyslogLens, createObjectURLCalls } = setUp();
  window.fetch = async () => ({ status: 401 });

  await SyslogLens.downloadIncidentReport();

  assert.equal(createObjectURLCalls.length, 0, 'no report should be downloaded when the session has expired');
});

test('a network failure (no server) still downloads a Log Summary report attributed to "unknown user"', async () => {
  const { window, SyslogLens, createObjectURLCalls } = setUp();
  window.fetch = async () => { throw new Error('network error'); };

  await SyslogLens.downloadSummaryReport();

  assert.equal(createObjectURLCalls.length, 1, 'the report should still download on a plain network failure');
  const html = await createObjectURLCalls[0].text();
  assert.match(html, /Generated by: unknown user/);
});

test('a network failure (no server) still downloads a Detailed Incident report attributed to "unknown user"', async () => {
  const { window, SyslogLens, createObjectURLCalls } = setUp();
  window.fetch = async () => { throw new Error('network error'); };

  await SyslogLens.downloadIncidentReport();

  assert.equal(createObjectURLCalls.length, 1, 'the report should still download on a plain network failure');
  const html = await createObjectURLCalls[0].text();
  assert.match(html, /Generated by: unknown user/);
});
